apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 5173 # Exposed service port
      targetPort: 5173 # Pod container port
      nodePort: 30080
  type: NodePort
